Algoritmo "crescente"

Var
      x, y : inteiro


Inicio

    escreva("Digite dois números: ")
    leia(x)
    leia(y)
    
    enquanto x <> y faca
    
       se x < y entao
            escreval("Crescente")
       senao
            escreval("Decrescente")
       fimse
       
       escreval("Digite outro dois numeros")
       leia(x)
       leia(y)
    
    fimenquanto

Fimalgoritmo